# Generated by Django 2.1.1 on 2018-09-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('phone', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('arrondissement', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('score', models.FloatField()),
                ('neighborhood', models.CharField(max_length=200)),
            ],
        ),
    ]
